### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Lucian-Williamson** [akhtarshahnawaz/multiprocesspandas#10]
[This](https://github.com/akhtarshahnawaz/multiprocesspandas/blob/main/multiprocesspandas/applyparallel.py#L30) has assumed an integer value to be given for n_chunks. And will throw a Type Error. Redefine n_chunks before throwing an assertion error.

**Comment by akhtarshahnawaz** [comment]
Thanks for pointing out.. 
Fixed it in new commit..
