### ISSUE TITLE
Add progressbar?

### ISSUE THREAD

**Issue by ebergam** [akhtarshahnawaz/multiprocesspandas#2]
Hi @akhtarshahnawaz , nice work!

Would you be interested in applying a progressbar to you library?

**Comment by wkaisertexas** [comment]
That would be ideal. 

When running a large data set and trying to use functional programming, the lack of a progress bar gets very annoying.

**Comment by akhtarshahnawaz** [comment]
> Hi @akhtarshahnawaz , nice work!
> 
> Would you be interested in applying a progressbar to you library?

Yes, it would be very interesting. 

I am a bit occupied in other works, but It could easily be achieved using TQDM. The resource below might help.
[Python Multiprocessing Progress Bar](https://clay-atlas.com/us/blog/2021/08/02/python-en-use-multi-processing-pool-progress-bar/)

Feel free to contribute and send a pull request.

**Comment by engnr-a** [comment]
Is this done ?

**Comment by akhtarshahnawaz** [comment]
Progress bar has been added.

**Comment by akhtarshahnawaz** [comment]
> Hi @akhtarshahnawaz , nice work!
> 
> Would you be interested in applying a progressbar to you library?

Check the latest version
