### ISSUE TITLE
It takes more time to apply a function while using apply_parallel()

### ISSUE THREAD

**Issue by sara-khorram** [akhtarshahnawaz/multiprocesspandas#4]
Hi and thanks for this package. I faced a problem while using it. I have a function that takes two values to calculate the third value. Surprisingly when I use regular apply function, it takes less time in comparison with using apply_parallel(). Is there anything that I did wrong? 
This is my code:
```
import pandas as pd
from multiprocesspandas import applyparallel

def calculate_new_features(value_1, value_2):
    new_value = ((value_1 ** 2) + (value_2 ** 2)) ** 0.5
    return new_value

def calculate_new_feature_row_based(row):
    new_feature = ((row['A'] ** 2) + (row['B'] ** 2)) ** 0.5
    return new_feature

df = pd.DataFrame(np.random.randint(0, 1000 ,size=(10000, 4)), columns=list('ABCD'))

# Without apply_parallel()
start_time = time.time()
df['F'] = df.apply(lambda row:calculate_new_features(row['A'], row['B']), axis=1)
running_time = time.time() - start_time
print(running_time)
# 0.3593626022338867 seconds

# Using apply_parallel()
start_time = time.time()
df['F'] = df.apply_parallel(calculate_new_feature_row_based, num_processes=4)
running_time = time.time() - start_time
print(running_time)
# 4.846656799316406 seconds

```

**Comment by akhtarshahnawaz** [comment]
Apply parallel function isn't ideal for parallelizing non-intensive functions on large number of individual rows. 
There is some overhead CPU time required to spin off new processes, so applying function on individual rows makes sense only if the function is very time consuming and number of samples is small. 
```

import pandas as pd
from multiprocesspandas import applyparallel
import numpy as np
import time

def calculate_new_features(value_1, value_2):
    new_value = sum([i for i in range(1000000)])
    return new_value

def calculate_new_feature_row_based(row):
    new_feature = sum([i for i in range(1000000)])
    return new_feature

df = pd.DataFrame(np.random.randint(0, 1000 ,size=(100, 4)), columns=list('ABCD'))

# Without apply_parallel()
start_time = time.time()
df['F'] = df.apply(lambda row:calculate_new_features(row['A'], row['B']), axis=1)
running_time = time.time() - start_time
print(running_time)
# 4.333596229553223 seconds

# Using apply_parallel()
start_time = time.time()
df['F'] = df.apply_parallel(calculate_new_feature_row_based, num_processes=4)
running_time = time.time() - start_time
print(running_time)
# 1.5801169872283936 seconds

```

It also makes sense if you are applying function on group of chunks at a time. Ideally, I should have implemented a version of apply function that can apply on a chuck of rows at a time, but same can be done by providing random grouping and then applying in parallel on each group separately.

**Comment by sara-khorram** [comment]
That's right. Thank you for your reponse.

**Comment by akhtarshahnawaz** [comment]
This shouldn't be a problem anymore in the new version. You just need to adjust n_chunks parameter to divided the whole dataset into chuncks to avoid IO bound delays.
