### ISSUE TITLE
[Question] Why attachpandas()?

### ISSUE THREAD

**Issue by MCRE-BE** [akhtarshahnawaz/multiprocesspandas#9]
Hey

I've been looking at your library and its implementation of multiprocessing to speed up some of my workflows, but I can't figure out the usecase for attachpandas function.

https://github.com/akhtarshahnawaz/multiprocesspandas/blob/b93601038ee9a8a2a059ded7c04e2b189cd56237/multiprocesspandas/applyparallel.py#L19-L22

I do understand that the implementation uses a monkey-patch way of adding features and not the new API provided by pandas itself, but I can't figure out why that function exists. It's not used either if I am not mistaken. These lines are more than enough if I look at the old documentation
https://github.com/akhtarshahnawaz/multiprocesspandas/blob/b93601038ee9a8a2a059ded7c04e2b189cd56237/multiprocesspandas/applyparallel.py#L48
https://github.com/akhtarshahnawaz/multiprocesspandas/blob/b93601038ee9a8a2a059ded7c04e2b189cd56237/multiprocesspandas/applyparallel.py#L71
https://github.com/akhtarshahnawaz/multiprocesspandas/blob/b93601038ee9a8a2a059ded7c04e2b189cd56237/multiprocesspandas/applyparallel.py#L108

BTW: likely best to one day move to the official API no?
https://pandas.pydata.org/pandas-docs/version/0.15/faq.html#adding-features-to-your-pandas-installation
https://stackoverflow.com/a/58705945/20716078

Thanks

**Comment by akhtarshahnawaz** [comment]
I agree that monkey patching could have been done without using the attach pandas function, but I just bundled all monkey patching in a function to keep them bundled together.

I wasn't aware that there is an official way to extend pandas functionality without monkey patching now. I agree that it's better to do that through official API, and I will try to do that for the next version. 

Feel free to implement that and push a merge request if you want to.

**Comment by MCRE-BE** [comment]
thanks for the feedback 😄 I'm quite a beginner so I was just trying to see if I understood everything. Nice to see the functools.partial btw. Solves a big part of my problem. 
I might implement it if I have some spare time.
